// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkkvplagwdvlmymmdjkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJra3ZwbGFnd2R2bG15bW1kamt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Mzc5ODksImV4cCI6MjA3NDIxMzk4OX0.dWV8HjQ-cCyeY4M1zw9p0BovBfx4CevmKyY7tDdOpdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});